### ISSUE TITLE
Limit the number of features

### ISSUE THREAD

**Issue by adalseno** [johnputmanii/numerai_xgb_eb#5]
First of all thank you very much for sharing your work.
I was wondering if it might be worth while to limit the number of selected features further based on their occurrence in the selection process. Something like this:
```
import os
import ast
from collections import Counter

all_features = []
dir_path = "./numerai_xgb_eb/borutashap/raw_results/"
for filename in os.listdir(dir_path):
    if "_20_eg" in filename: 
        with open(dir_path + filename, 'r') as f:
            l1 = ast.literal_eval(f.readline().split(":")[1].strip())
            #print(filename, len(l1), type(l1))
            all_features += l1
print("Unique features for '_20_' target:",len(set(all_features)))
feat_count = Counter(all_features).most_common()
cutoff = 5
print(f'Selected features that appear at least {cutoff} times: {len([feat for feat, val in feat_count if val >= cutoff])}')
```
Result:
```
Unique features for '_20_' target: 173
Selected features that appear at least 5 times: 63
```
What do you think?

**Comment by johnputmanii** [comment]
@adalseno Thank you for the input. If you move up one in the directory to borutashap/ you'll see a list of feature sets that have been compiled from the raw output. I think this accomplishes what you're requesting. As an example, the best_plus feature set takes all of the "important" and all of the "tentative" features from all of the raw files and removes all the duplicates. This leaves us with 622 "unique" features for training.

https://github.com/johnputmanii/numerai_xgb_eb/blob/main/borutashap/best_plus_all_targets.csv

**Comment by adalseno** [comment]
Hi @johnputmanii , thank you very much for your kind reply. Actually my point was slightly different. I scanned all the feature files and counted how may times a feature appeared as important so that I may further reduce the number of features. For example, limiting the analysis to the "_20_" target (40 files, 10 targets for 4 era groups), I found out that "feature_haziest_lifelike_horseback" was listed 32 times while "feature_unsealed_suffixal_babar" appeared just once. 

One can easily extend the logic to include any other case to create his own mix. Using a cutoff= 5 the 622 unique features (important and tentative) will be reduced to 366 or using a cutoff of 5 for important and 10 for tentative will give us "just" 258 features.
This to create a dict from the files for convenience (adjust the path if needed):
```
import os
import ast
from collections import Counter
import json
# Create dict form file targets
all_features = {}
dir_path = "borutashap/raw_results/"
for filename in os.listdir(dir_path):
    if filename.endswith(".txt"): 
        group = filename.replace('.txt', '')
        all_features[group] = {}
        with open(dir_path + filename, 'r') as f:
            for line in f:
                l1 = line.split(":")
                all_features[group]["".join([i for i in l1[0] if not i.isdigit()]).strip()] = ast.literal_eval(l1[1].strip())
# Save to json file            
with open('feature_dict.json', 'w') as f:
    json.dump(all_features, f)
```
Then we can easily combine the features as we like:
```
important_features = []
possible_features = []
for key, value in all_features.items():
    important_features+= value['attributes confirmed important']
    possible_features += value['tentative attributes remains']
print(f"Unique important features {len(set(important_features))} out of {len(important_features)}")
print(f"Unique tentative features {len(set(possible_features))} out of {len(possible_features)}")
print(f"Unique important features + possible features {len(set(important_features+possible_features))} out of {len(important_features+possible_features)}")
important_feat_count = Counter(important_features).most_common()
possible_feat_count = Counter(possible_features).most_common()
cutoff = 5
selected_features_c5 = list(set([feat for feat, val in important_feat_count if val >= cutoff]+[feat for feat, val in possible_feat_count if val >= cutoff+5]))
print(f'Selected features that appear at least {cutoff} times as important and {cutoff + 5} as tentative: {len(selected_features_c5)}')
```
Will give this out_put:
```
Unique important features 345 out of 3517
Unique possible features 612 out of 4257
Unique important features + possible features 622 out of 7774
Selected features that appear at least 5 times as important and 10 as tentative: 258
```

**Comment by johnputmanii** [comment]
@adalseno I'm finally on the same page. Really nice work. I know we had one or two people in the community that wanted to build models from weak learners as well, in addition to increased dimensionality reduction and the unique sets, I think we can target those unimportant feats with this.

 If you'd like to generate a PR for the above code, do so whenever you have time. I'll add it manually if you don't have time. Thanks again.

**Comment by adalseno** [comment]
Yes, sure. I think the best place is utility.py, isn't it?
Regards,
Andrea






Il martedì 30 novembre 2021, 16:41:57 CET, John E. Putman II ***@***.***> ha scritto: 







@adalseno I'm finally on the same page. Really nice work. I know we had one or two people in the community that wanted to build models from weak learners as well, in addition to increased dimensionality reduction and the unique sets, I think we can target those unimportant feats with this.

If you'd like to generate a PR for the above code, do so whenever you have time. I'll add it manually if you don't have time. Thanks again.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adalseno** [comment]
Hi, pull request added. As you will see in the comment, I've also added a .gitignore file (using github python template, in order to avoid to upload useless files) and I'd also suggest to remove the __pycahce__ dir from the repo.


regards,
Andrea



Il martedì 30 novembre 2021, 16:41:57 CET, John E. Putman II ***@***.***> ha scritto: 







@adalseno I'm finally on the same page. Really nice work. I know we had one or two people in the community that wanted to build models from weak learners as well, in addition to increased dimensionality reduction and the unique sets, I think we can target those unimportant feats with this.

If you'd like to generate a PR for the above code, do so whenever you have time. I'll add it manually if you don't have time. Thanks again.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by johnputmanii** [comment]
@adalseno Everything looks good. Thanks for all the help!
Removed the pycache per your suggestion as well.
